#!/bin/sh
#        _                        _            ___  _  _   
#   __ _| | _____  _____ ___   __| | ___ _ __ / _ \| || |  
#  / _` | |/ _ \ \/ / __/ _ \ / _` |/ _ \ '__| | | | || |_ 
# | (_| | |  __/>  < (_| (_) | (_| |  __/ |  | |_| |__   _|
#  \__,_|_|\___/_/\_\___\___/ \__,_|\___|_|   \___/   |_|  
# 
# Copyright (c) 2021 alexcoder04 <https://github.com/alexcoder04>
# 
# select a configuration for newsboat and start it

. libsh || exit 1

chosen_topic="$(/bin/ls "$HOME/.config/newsboat/"*.urls \
  | rev | cut -d"/" -f1 | rev | cut -d"." -f1 \
  | prompt_gui "RSS")"

[ -z "$chosen_topic" ] && exit

exec newsboat \
  -u "$XDG_CONFIG_HOME/newsboat/$chosen_topic.urls" \
  -c "$XDG_CACHE_HOME/newsboat/$chosen_topic.cache"

