#!/bin/sh
#        _                        _            ___  _  _   
#   __ _| | _____  _____ ___   __| | ___ _ __ / _ \| || |  
#  / _` | |/ _ \ \/ / __/ _ \ / _` |/ _ \ '__| | | | || |_ 
# | (_| | |  __/>  < (_| (_) | (_| |  __/ |  | |_| |__   _|
#  \__,_|_|\___/_/\_\___\___/ \__,_|\___|_|   \___/   |_|  
# 
# Copyright (c) 2022 alexcoder04 <https://github.com/alexcoder04>
# 
# newsboat-iv: image viewer for the newsboat RSS reader

. libsh || exit 1

cd "${TMPDIR:-/tmp}"
link="$(grep -E '^\[[0-9]+\]: http(s)?://.* \(image\)$' /dev/stdin \
  | rev | cut -d" " -f2- | rev \
  | prompt_gui "img" \
  | cut -d" " -f2-)"

[ -z "$link" ] && exit 0

basename="${link##*/}"
dlname="newsboat-$(printf '%s' "$link" | md5sum | cut -d" " -f1)-$basename"

[ ! -f "$dlname" ] && wget -q -O "$dlname" "$link"

setsid nsxiv -q "$dlname" &

